version: '3'
services:
    mysql:
        image: mysql:5.7
        container_name: agenda_mysql
        environment:
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD : "true"
            MYSQL_DATABASE: agenda
        ports:
            - "3306"
        networks: 
            - production-network
networks:
    production-network:
        driver: bridge