version: '3.3'
services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: agenda
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
        expose: 
            - "3306"
        networks: 
         - production-network
networks:
    production-network:
        driver: bridge
        name: production-network
